databases:
  - name: traveler
    databaseName: traveler_qise
    user: user
    region: Oregon

services:
  - type: web
    name: traveler
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    # startCommand: ./bin/rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: traveler
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2